// MUX

#define MUX_CHANNELS 16

#define MUX_OSC_1_GAIN 0
#define MUX_OSC_2_GAIN 1
#define MUX_OSC_2_OCTAVE 2
#define MUX_OSC_2_DETUNE 3
#define MUX_FILTER_CUTOFF 4
#define MUX_FILTER_RESONANCE 5
#define MUX_OSC_1_WAVEFORM 6
#define MUX_OSC_2_WAVEFORM 7
#define MUX_AMP_ADSR_ATTACK 8
#define MUX_AMP_ADSR_DECAY 9
#define MUX_AMP_ADSR_SUSTAIN 10
#define MUX_AMP_ADSR_RELEASE 11
#define MUX_FILTER_LFO_LEVEL 12
#define MUX_FILTER_LFO_RATE 13
#define MUX_PWM_LEVEL 14
#define MUX_PWM_RATE 15

#define MUX2_FILTER_LFO_WAVEFORM 0
#define MUX2_PWM_LFO_WAVEFORM 1